backend/backend/urls.py
# urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers
from oglasnik.views import ZupanijaViewSet, GradViewSet, KorisnikViewSet, KategorijaViewSet, OglasViewSet, SlikaViewSet, FavoritViewSet, KomentarViewSet
from oglasnik.views import registracija, trenutni_korisnik, profil, kreiraj_oglas, moji_oglasi, izbrisi_oglas, uredi_oglas, dohvati_korisnika, admin_view, arhiviraj_oglas
from oglasnik.views import oglasi_po_kategoriji, oglas_detalji, odjavi_korisnika, pretraga_oglasi, azuriraj_oglas, azuriraj_korisnika, promjena_lozinke, azuriraj_korisnika_admin
from django.contrib.auth import views as auth_views
from rest_framework_simplejwt import views as jwt_views
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static
def home(request):
    return redirect('http://localhost:3000/')

router = routers.DefaultRouter()
router.register(r'zupanije', ZupanijaViewSet)
router.register(r'gradovi', GradViewSet)
router.register(r'korisnici', KorisnikViewSet)
router.register(r'kategorije', KategorijaViewSet)
router.register(r'oglasi', OglasViewSet)
router.register(r'slike', SlikaViewSet)
router.register(r'favoriti', FavoritViewSet)
router.register(r'komentari', KomentarViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('api/trenutni_korisnik/', trenutni_korisnik, name='trenutni_korisnik'),
    path('', home, name='home'),
    path('oglasi/<str:url>/', oglasi_po_kategoriji, name='oglasi_po_kategoriji'),
    path('korisnik/<str:username>/', dohvati_korisnika, name='korisnik_detail'),
    path('api/kreiraj_oglas/', kreiraj_oglas, name='kreiraj_oglas'),
    path('api/azuriraj_oglas/<int:oglas_id>/', azuriraj_oglas, name='azuriraj_oglas'),
    path('api/moji_oglasi/', moji_oglasi, name='moji_oglasi'),
    path('api/oglas/<int:pk>/izbrisi/', izbrisi_oglas, name='izbrisi_oglas'),
    path('api/oglas/<int:pk>/arhiviraj/', arhiviraj_oglas, name='arhiviraj_oglas'),
    path('api/odjava/', odjavi_korisnika, name='logout_user'),
    path('registracija/', registracija, name='registracija'),
    path('azuriraj-korisnika/', azuriraj_korisnika, name='azuriraj_korisnika'),
    path('promjena-lozinke/', promjena_lozinke, name='promjena_lozinke'),
    path('prijava/', auth_views.LoginView.as_view(template_name='prijava.html', success_url='localhost:3000/'), name='prijava'),
    path('profil/', profil, name='profil'),
    path('api/pretraga/', pretraga_oglasi, name='pretraga_oglasi'),
    path('favoriti/dodaj/', FavoritViewSet.as_view({'post': 'dodaj'}), name='dodaj-favorit'),
    path('favoriti/ukloni/', FavoritViewSet.as_view({'delete': 'ukloni'}), name='ukloni-favorit'),
    path('favoriti/moji_favoriti/', FavoritViewSet.as_view({'get': 'moji_favoriti'}), name='moji-favoriti'),
    path('oglas/<str:sifra>/', oglas_detalji, name='oglas_detalji'),
    path('admin-panel/', admin_view, name='admin-panel'),
    path('admin-panel/azuriraj-korisnika/<int:user_id>/', azuriraj_korisnika_admin, name='azuriraj_korisnika_admin'),
    path('<str:kategorija_url>/uredi/<str:oglas_naziv>-oglas-<str:sifra>/', uredi_oglas, name='uredi_oglas'),
    path('izbrisi_oglas/<int:oglas_id>/', izbrisi_oglas, name='izbrisi_oglas'),  
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/oglasnik/models.py
# models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
import uuid
from django.utils import timezone

class Zupanija(models.Model):
    naziv = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name = 'Zupanije'
        verbose_name_plural = 'Zupanije'
        
    def __str__(self):
        return self.naziv

class Grad(models.Model):
    zupanija = models.ForeignKey(Zupanija, on_delete=models.CASCADE)
    naziv = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Grad'
        verbose_name_plural = 'Gradovi'

    def __str__(self):
        return self.naziv

class Korisnik(AbstractUser):
    oib = models.CharField(max_length=11, null=True, validators=[RegexValidator(r'^\d{11}$', message='OIB mora imati 11 znamenki')])
    zupanija = models.ForeignKey(Zupanija, on_delete=models.CASCADE, null=True)
    grad = models.ForeignKey(Grad, on_delete=models.SET_NULL, null=True)
    telefon = models.CharField(max_length=12, null=True, blank=True, validators=[RegexValidator(r'^\d{6,12}$', message='Telefon mora imati između 6 i 12 znamenki')])

    class Meta:
        verbose_name = 'Korisnik'
        verbose_name_plural = 'Korisnici'

    def __str__(self):
        return self.username
    
class Kategorija(models.Model):
    naziv = models.CharField(max_length=100)
    roditelj = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    url = models.CharField(max_length=100, unique=True, null=True, blank=True)

    class Meta:
        verbose_name = 'Kategorija'
        verbose_name_plural = 'Kategorije'

    def __str__(self):
        return self.naziv

class Oglas(models.Model):
    IZBOR_TRAJANJA = [
        (1, '1 dan'),
        (7, '1 tjedan'),
        (30, '1 mjesec'),
    ]
    STATUS_IZBORI = [
        ('aktivan', 'Aktivan'),
        ('neaktivan', 'Neaktivan'),
        ('arhiviran', 'Arhiviran')
    ]
    def generiraj_sifru():
        while True:
            sifra = str(uuid.uuid4().int)[:8]
            if not Oglas.objects.filter(sifra=sifra).exists():
                return sifra

    cijena = models.DecimalField(max_digits=10, decimal_places=2)
    sifra = models.CharField(default=generiraj_sifru, editable=False, unique=True, max_length=8)
    naziv = models.CharField(max_length=255)
    opis = models.TextField()
    korisnik = models.ForeignKey(Korisnik, on_delete=models.CASCADE)
    zupanija = models.ForeignKey(Zupanija, on_delete=models.CASCADE)
    grad = models.ForeignKey(Grad, on_delete=models.CASCADE)
    trajanje = models.IntegerField(choices=IZBOR_TRAJANJA)
    kategorija = models.ForeignKey(Kategorija, on_delete=models.CASCADE, null=True)
    datum = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=10, choices=STATUS_IZBORI, default='aktivan')

    class Meta:
        verbose_name = 'Oglas'
        verbose_name_plural = 'Oglasi'

    def __str__(self):
        return self.naziv

class Pregled(models.Model):
    oglas = models.ForeignKey(Oglas, on_delete=models.CASCADE)
    ip_address = models.GenericIPAddressField()
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('oglas', 'ip_address', 'timestamp')
        verbose_name = 'Pregled'
        verbose_name_plural = 'Pregledi'
        
class Slika(models.Model):
    oglas = models.ForeignKey(Oglas, on_delete=models.CASCADE, related_name='slike')
    slika = models.ImageField(upload_to='slike/')

    class Meta:
        verbose_name = 'Slika'
        verbose_name_plural = 'Slike'
    def __str__(self):
        return f"Slika za {self.oglas.naziv}"

class Favorit(models.Model):
    korisnik = models.ForeignKey(Korisnik, on_delete=models.CASCADE, related_name='favoriti')
    oglas = models.ForeignKey(Oglas, on_delete=models.CASCADE, related_name='favoriti')
    datum = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('korisnik', 'oglas')
        verbose_name = 'Favorit'
        verbose_name_plural = 'Favoriti'

    def __str__(self):
        return f"{self.korisnik.username} - {self.oglas.naziv}"
    
class Komentar(models.Model):
    korisnik = models.ForeignKey(Korisnik, related_name='komentari', on_delete=models.CASCADE)
    autor = models.ForeignKey(Korisnik, related_name='napisani_komentari', on_delete=models.CASCADE)
    tekst = models.CharField(max_length=150)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Komentar'
        verbose_name_plural = 'Komentari'
        ordering = ['-timestamp']

    def __str__(self):
        return f'Komentar od {self.autor.username} za {self.korisnik.username}'

backend/oglasnik/forms.py
# forms.py 
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Korisnik, Zupanija, Grad, Oglas, Slika
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _
from django.core.validators import RegexValidator
from django.contrib.auth.forms import PasswordChangeForm

class FormaZaRegistraciju(UserCreationForm):
    zupanija = forms.ModelChoiceField(queryset=Zupanija.objects.all(), empty_label=_("Odaberi županiju"), label=_("Županija"))
    grad = forms.ModelChoiceField(queryset=Grad.objects.none(), empty_label=_("Odaberi grad"), label=_("Grad"))
    telefon = forms.CharField(max_length=12, validators=[RegexValidator(r'^\d{6,12}$', message=_("Telefon mora imati između 6 i 12 znamenki"))], required=False)
    
    class Meta(UserCreationForm.Meta):
        model = Korisnik
        fields = ['username', 'email', 'password1', 'password2', 'first_name', 'last_name', 'oib', 'zupanija', 'grad', 'telefon']
        labels = {
            'username': _('Korisničko ime'),
            'email': _('Email'),
            'password1': _('Lozinka'),
            'password2': _('Ponovite lozinku'),
            'first_name': _('Ime'),
            'last_name': _('Prezime'),
            'oib': _('OIB'),
            'zupanija': _('Županija'),
            'grad': _('Grad'),
            'telefon': _('Telefon')
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if 'zupanija' in self.data:
            try:
                zupanija_id = int(self.data.get('zupanija'))
                self.fields['grad'].queryset = Grad.objects.filter(zupanija_id=zupanija_id)
            except (ValueError, TypeError):
                pass
        elif self.instance.zupanija_id:
            self.fields['grad'].queryset = Grad.objects.filter(zupanija_id=self.instance.zupanija_id)

class VisestrukiUnosDatoteka(forms.ClearableFileInput):
    allow_multiple_selected = True

class VisestrukaDatoteka(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", VisestrukiUnosDatoteka())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        ciscenje_jedne_datoteke = super().clean
        if isinstance(data, (list, tuple)):
            rezultat = [ciscenje_jedne_datoteke(d, initial) for d in data]
        else:
            rezultat = ciscenje_jedne_datoteke(data, initial)
        return rezultat

class SlikaForma(forms.ModelForm):
    class Meta:
        model = Slika
        fields = ['slika']


class FormaZaIzraduOglasa(forms.ModelForm):
    MAX_VELICINA_SLIKE = 5 * 1024 * 1024  # 5MB u bytovima
    MAX_BROJ_SLIKA = 4

    class Meta:
        model = Oglas
        fields = ['cijena', 'naziv', 'opis', 'zupanija', 'grad', 'trajanje', 'kategorija']

    def clean(self):
        cleaned_data = super().clean()
        slike = self.files.getlist('slike')  # Get list of uploaded image files

        if len(slike) > self.MAX_BROJ_SLIKA:
            raise ValidationError(f'Možete odabrati maksimalno {self.MAX_BROJ_SLIKA} slike.')

        for img in slike:
            if img.size > self.MAX_VELICINA_SLIKE:
                raise ValidationError('Slika ne smije biti veća od 5MB.')

        return cleaned_data


class AzuriranjeKorisnikaForma(forms.ModelForm):
    zupanija = forms.ModelChoiceField(queryset=Zupanija.objects.all(), empty_label=_("Odaberi županiju"), label=_("Županija"))
    grad = forms.ModelChoiceField(queryset=Grad.objects.none(), empty_label=_("Odaberi grad"), label=_("Grad"))
    telefon = forms.CharField(max_length=12, validators=[RegexValidator(r'^\d{6,12}$', message=_("Telefon mora imati između 6 i 12 znamenki"))], required=False)
    
    class Meta:
        model = Korisnik
        fields = ['email', 'first_name', 'last_name', 'oib', 'zupanija', 'grad', 'telefon']
        labels = {
            'email': _('Email'),
            'first_name': _('Ime'),
            'last_name': _('Prezime'),
            'oib': _('OIB'),
            'zupanija': _('Županija'),
            'grad': _('Grad'),
            'telefon': _('Telefon')
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if 'zupanija' in self.data:
            try:
                zupanija_id = int(self.data.get('zupanija'))
                self.fields['grad'].queryset = Grad.objects.filter(zupanija_id=zupanija_id)
            except (ValueError, TypeError):
                pass
        elif self.instance.zupanija_id:
            self.fields['grad'].queryset = Grad.objects.filter(zupanija_id=self.instance.zupanija_id)

    def clean_oib(self):
        oib = self.cleaned_data['oib']
        if Korisnik.objects.exclude(pk=self.instance.pk).filter(oib=oib).exists():
            raise ValidationError(_('OIB već postoji.'))
        return oib

class PromjenaLozinkeForma(PasswordChangeForm):
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Stara lozinka'}))
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Nova lozinka'}))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Ponovite novu lozinku'}))

    class Meta:
        fields = ['old_password', 'new_password1', 'new_password2']
        

        

backend/oglasnik/templates/kreiraj_oglas.html
<!-- kreiraj_oglas.html -->
{% load static %}
<!DOCTYPE html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Kreiraj Oglas</title>
    <!-- Include jQuery library -->
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/dropdown.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            // Multiple file upload handling
            $('#id_slike').on('change', function(){
                var files = $(this).get(0).files;
                var fileNames = '';
                for (var i = 0; i < files.length; i++) {
                    fileNames += files[i].name + ', ';
                }
                // Display selected file names
                $('#selected-files').text(fileNames);
            });
        });
    </script>
    
</head>
<body>
    <a href="http://localhost:3000/">Natrag na početnu</a>
    <h2>Kreiraj Oglas</h2>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Kreiraj Oglas</button>
</form>

</body>
</html>

backend/oglasnik/templates/moji_oglasi.html
<!DOCTYPE html>
<html lang="hr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Moji oglasi</title>
    <style>
        .oglas-image {
            max-width: 200px;
            height: auto;
        }
    </style>
</head>

<body>
    <a href="http://localhost:3000/">Natrag na početnu</a>
    <h2 className="text-xl mb-4">Moji oglasi</h2>
    <p><strong>Broj oglasa:</strong> {{ oglasi|length }}</p>
    <ul>
        {% for oglas in oglasi %}
        <li>
            <strong>Naziv:</strong> <a href="{% url 'uredi_oglas' kategorija_url=oglas.kategorija.url oglas_naziv=oglas.naziv sifra=oglas.sifra %}">{{ oglas.naziv }}</a><br>
            <strong>Cijena:</strong> {{ oglas.cijena }} €<br>
            <strong>Opis:</strong> {{ oglas.opis }}<br>
            <strong>Datum:</strong> {{ oglas.datum|date:"d/m/Y H:i" }}<br>
            <strong>Trajanje:</strong> {{ oglas.get_trajanje_display }}<br>
            <strong>Županija:</strong> {{ oglas.zupanija.naziv }}<br>
            <strong>Grad:</strong> {{ oglas.grad.naziv }}<br>
            <strong>Kategorija:</strong>
            {% if oglas.kategorija %}
            {{ oglas.kategorija.naziv }}
            {% if oglas.kategorija.roditelj %}
            ({{ oglas.kategorija.roditelj.naziv }})
            {% endif %}
            {% else %}
            N/A
            {% endif %}<br>
            {% if oglas.slike.exists %}
            {% for slika in oglas.slike.all %}
            <img src="data:image/jpeg;base64,{{ slika.slika }}" alt="Slika oglasa" class="oglas-image">
            {% endfor %}
            {% else %}
            Nema slika.
            {% endif %}
            <form action="{% url 'izbrisi_oglas' oglas_id=oglas.id %}" method="post">
                {% csrf_token %}
                <button type="submit">Izbriši oglas</button>
            </form>
        </li>
        {% empty %}
        <li>Nema oglasa.</li>
        {% endfor %}
    </ul>
</body>

</html>

backend/oglasnik/templates/oglas_detalji.html
<!-- oglas_detalji.html -->
<!DOCTYPE html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Detalji oglasa</title>
</head>
<body>
    <p>
        <a href="http://localhost:3000/">Oglasnik</a>
        {% for kat in hijerarhija %}
            > <a href="{% url 'oglasi_po_kategoriji' kat.url %}">{{ kat.naziv }}</a>
        {% endfor %}
    </p>

    <h2>{{ oglas.naziv }}</h2>
    <p>{{ oglas.opis }}</p>

    <h3>Slike:</h3>
    {% for slika in slike %}
        <img src="data:image/png;base64,{{ slika.slika }}" alt="Slika oglasa">
    {% endfor %}

    <p>Autor oglasa: {{ oglas.korisnik.username }}</p>
</body>
</html>

backend/oglasnik/templates/oglasi_po_kategoriji.html
<!-- oglasi_po_kategoriji.html  -->
<!DOCTYPE html>
<html lang="hr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Oglasi po kategoriji</title>
</head>
<body>
    <p>
        <a href="http://localhost:3000/">Natrag na početnu</a>
        {% for kat in hijerarhija %}
            > <a href="{% url 'oglasi_po_kategoriji' kat.url %}">{{ kat.naziv }}</a>
        {% endfor %}
    </p>

    <h2>Oglasi po kategoriji: {{ kategorija.naziv }}</h2>

    <h3>Podkategorije:</h3>
    <ul>
        {% for kat in kategorija.children.all %}
            <li><a href="{% url 'oglasi_po_kategoriji' kat.url %}">{{ kat.naziv }}</a></li>
        {% endfor %}
    </ul>

    <h3>Oglasi:</h3>
    <ul>
        {% for oglas in oglasi %}
            <li>
                <a href="{% url 'oglas_detalji' oglas.kategorija.url oglas.naziv oglas.sifra %}">
                    <h4>{{ oglas.naziv }}</h4>
                </a>
                {% if oglas.slike.all %}
                    <img src="data:image/png;base64,{{ oglas.slike.all.0.slika }}" alt="{{ oglas.naziv }}" style="max-width: 100px; max-height: 100px;">
                {% endif %}
                <p>{{ oglas.opis|truncatewords:20 }}</p>
                <p>Cijena: {{ oglas.cijena }} €</p>
            </li>
        {% endfor %}
    </ul>
</body>
</html>

backend/oglasnik/templates/pocetna.html
<!-- pocetna.html -->
<!DOCTYPE html>
<html lang="hr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dobrodošli</title>
</head>

<body>
    <h2>Dobrodošli!</h2>
    {% if korisnik.is_authenticated %}
    <p>Prijavljeni ste kao: {{ korisnik.username }}</p>
    <form action="{% url 'odjava' %}" method="post">
        {% csrf_token %}
        <button type="submit">Odjava</button>
    </form>
    {% else %}
    <a href="{% url 'prijava' %}">Prijava</a>
    <a href="{% url 'registracija' %}">Registracija</a>
    {% endif %}
    </ul>
</body>

</html>

backend/oglasnik/templates/prijava.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Prijava</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>

<body>
    <div class="container">
        <h2>Prijava</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Prijavi se</button>
        </form>
        <p>Nemate korisnički račun? <a href="{% url 'registracija' %}">Registrirajte se ovdje</a>.</p>
    </div>
</body>

</html>

backend/oglasnik/templates/profil.html
<!-- profil.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profil</title>
</head>
<body>
    <h2>Profil</h2>
    <p>Korisničko ime: {{ user.username }}</p>
    <p>Ime: {{ user.first_name }}</p>
    <p>Prezime: {{ user.last_name }}</p>
    <p>Email: {{ user.email }}</p>
    <p>Datum pridruživanja: {{ user.date_joined }}</p>
    <a href="http://localhost:3000/">Natrag na početnu</a>
</body>
</html>

backend/oglasnik/templates/registracija.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registracija Korisnika</title>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/dropdown.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/registracija.css' %}">
</head>
<body>
    <div class="container">
        <h2>Registracija Korisnika</h2>
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.help_text %}
                        <small class="form-text text-muted">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                        <div class="error">{{ error }}</div>
                    {% endfor %}
                </div>
            {% endfor %}
            <button type="submit">Submit</button>
        </form>
    </div>
</body>
</html>

backend/oglasnik/templates/uredi_oglas.html
<!DOCTYPE html>
<html lang="hr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Uredi oglas</title>
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        form {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            border: 1px solid #ccc;
            border-radius: 5px;
            background-color: #f9f9f9;
        }

        h2 {
            text-align: center;
        }

        img {
            max-width: 100%;
            height: auto;
            margin-bottom: 10px;
            display: block;
        }

        label {
            font-weight: bold;
        }

        button {
            display: block;
            width: 100%;
            padding: 10px;
            background-color: #007bff;
            color: #fff;
            border: none;
            border-radius: 5px;
            cursor: pointer;
            margin-top: 10px;
        }

        button:hover {
            background-color: #0056b3;
        }
    </style>
</head>

<body>
    <a href="http://localhost:3000/">Natrag na početnu</a>
    <h2>Uredi oglas</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        
        {% for slika in form.instance.slike.all %}
            <img src="data:image/jpeg;base64,{{ slika.slika }}" alt="Slika oglasa">
            <input type="checkbox" name="delete_slike" value="{{ slika.id }}"> Obrisi sliku<br>
        {% endfor %}
        
        <label for="id_slike">Dodaj nove slike:</label>
        <input type="file" name="slike" id="id_slike" multiple>

        
        <button type="submit">Spremi promjene</button>
    </form>
</body>

</html>